### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by xirami** [arnauorriols/node-red-contrib-python-function#13]
Hi,

in order to have successfully working Python 3 code on Debian kind of systems, command has to be changed to 
```JavaScript
    function spawnFn(self) {
        self.child = spawn('python3', ['-uc', self.func.code], {
            stdio: ['pipe', 'pipe', 'pipe', 'ipc']
        });
```

**Comment by noobydp** [comment]
I also have this issue. I'm running Node-Red in docker on Unraid, and it has both python and python3.
This module always uses python (i.e. v2)

**Comment by tedvdb** [comment]
It would be nice if someone would implement a "python selector" that allows us to pick which python interpreter should be used.
I'm not skilled enough in JS to implement this tough. 😞

**Comment by DPAmes** [comment]
Same issue. Took me a while to figure out why my included library was crashing with a syntax error.
I'm not sure how to incorporate ondrejspilka's solution. I'll try to figure it out.

**Comment by jacobgarder** [comment]
Same issue with the official [docker image](https://hub.docker.com/r/nodered/node-red/), version 3.0.2.
