### ISSUE TITLE
Threading is not working ????

### ISSUE THREAD

**Issue by krambriw** [arnauorriols/node-red-contrib-python-function#5]
This simple code is not working:

```
from threading import Timer

def wakeUpCall():
    node.warn('time to wake up')

t = Timer(5.0, wakeUpCall)
t.start()
node.warn('waiting for timer to fire')


```

**Comment by arnauorriols** [comment]
It does work. As in #10 , remember that an input message is necessary to _trigger_ the code. You can have a dummy trigger that triggers automatically at boot if you just want to run the Python code...

**Comment by lorenzanaj** [comment]
I can confirm this works with at least with my stepper motor task. 2 simple threads were spawned, did some gpio/driver type things and joined and completed fine.
